### ISSUE TITLE
Update reserved keywords

### ISSUE THREAD

**Issue by mikucionisaau** [UPPAALModelChecker/docs.uppaal.org#42]
The section on keywords need to be updated to include new query features (`minE`, `maxE`).

**Comment by thorulf4** [comment]
Interestingly minE and maxE are not yet keywords

**Comment by thorulf4** [comment]
Similar issue exists with Pr as that is also a token. Maybe we should switch to an inline matching like with E in value estimation queries. But E is not a keyword and does not cause issues
