### ISSUE TITLE
The decrement operator is rendered incorrectly because of markdown magic

### ISSUE THREAD

**Issue by thorulf4** [UPPAALModelChecker/docs.uppaal.org#49]
https://github.com/UPPAALModelChecker/docs.uppaal.org/blob/cae0ed8b761a27c054b456c2a0b1d3dd7856ef5e/content/language-reference/expressions/_index.md?plain=1#L84

Because Hugo uses markdown -- is combined into a –
![image](https://github.com/UPPAALModelChecker/docs.uppaal.org/assets/10059450/8dd948e9-1096-4735-922c-f676b2cac3fc)

**Comment by mikucionisaau** [comment]
I'll enclose all those expressions in back-ticks, which enforces monospace font and then they appear correctly.
