### ISSUE TITLE
Document FFI

### ISSUE THREAD

**Issue by yrke** [UPPAALModelChecker/docs.uppaal.org#6]
Missing documentation of expert feature FFI https://github.com/UPPAALModelChecker/UPPAAL-Meta/issues/22
Specification in https://vbn.aau.dk/ws/files/280720003/2017_ICECCS_Nyman.pdf

**Comment by petergjoel** [comment]
The example given here: https://docs.uppaal.org/language-reference/system-description/declarations/external-functions/
is a little problematic as it promotes side-effects/hidden state in the C-code.
